# Converts the vendored Chromium vector commands without changing their geometry.
# Run from any directory; no network access or build-time dependency is required.
$ErrorActionPreference = 'Stop'
$output = Join-Path $PSScriptRoot '..\..\Quartz\Resources\ChromiumMenus'
New-Item -ItemType Directory -Force $output | Out-Null
$commands = @{
    MOVE_TO = @('M', 2); R_MOVE_TO = @('m', 2)
    LINE_TO = @('L', 2); R_LINE_TO = @('l', 2)
    ARC_TO = @('A', 7); R_ARC_TO = @('a', 7)
    CUBIC_TO = @('C', 6); R_CUBIC_TO = @('c', 6)
    CLOSE = @('Z', 0)
}
foreach ($name in @('check', 'keyboard_arrow_right_flippable')) {
    $source = Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot "icons\$name.icon")
    $tokens = ([regex]::Replace($source, '//[^\r\n]*', '') -split ',').Trim() | Where-Object { $_ }
    $paths = [System.Collections.Generic.List[string]]::new()
    $canvas = $null
    for ($i = 0; $i -lt $tokens.Count; $i++) {
        $command = $tokens[$i]
        if ($command -eq 'CANVAS_DIMENSIONS') { $canvas = $tokens[++$i]; continue }
        if ($command -in @('FLIPS_IN_RTL', 'FILL_RULE_NONZERO')) { continue }
        if (!$commands.ContainsKey($command)) { throw "Unsupported Chromium command: $command" }
        $mapping = $commands[$command]
        $values = for ($j = 0; $j -lt $mapping[1]; $j++) {
            $value = $tokens[++$i] -replace 'f$', ''
            if ($value -notmatch '^-?\d+(\.\d+)?$') { throw "Invalid coordinate: $value" }
            $value
        }
        $paths.Add(($mapping[0] + ($values -join ' ')))
    }
    if (!$canvas) { throw "Missing canvas in $name.icon" }
    $svg = @"
<!-- Copyright 2026 The Chromium Authors. BSD license: chromeium/context_menu/LICENSE.
     Generated by chromeium/context_menu/convert-icons.ps1 from the original $name.icon. -->
<svg xmlns="http://www.w3.org/2000/svg" width="$canvas" height="$canvas" viewBox="0 0 $canvas $canvas">
  <path fill-rule="nonzero" d="$($paths -join ' ')" />
</svg>
"@
    [IO.File]::WriteAllText((Join-Path $output "$name.svg"), $svg + "`n", [Text.UTF8Encoding]::new($false))
}
